package com.cts.eventsphere.iamservice.model;

import com.cts.eventsphere.iamservice.model.data.UserRoles;
import com.cts.eventsphere.iamservice.model.data.UserStatus;
import jakarta.persistence.*;
import lombok.Data;
import org.hibernate.annotations.CreationTimestamp;

import java.time.LocalDateTime;

/**
 * JPA entity representing a registered user in the EventSphere platform.
 *
 * <p>Stores all persistent user information including identity details, credentials,
 * assigned role, account status, and audit timestamps. The primary key ({@code userId})
 * is a UUID generated by the database.</p>
 *
 * <p>Default values on creation: {@code role = ATTENDEE}, {@code status = ACTIVE}.</p>
 *
 * @author 2480010
 * @version 1.0
 * @since 25-03-2026
 */
@Entity
@Data
public class User {
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @Column(columnDefinition = "CHAR(36)")
    private String userId;

    @Column(nullable = false, length = 100)
    private String name;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private UserRoles role = UserRoles.ATTENDEE;

    @Column(nullable = false, length = 100)
    private String email;

    @Column(nullable = false, length = 255)
    private String password;

    @Column(nullable = false, length = 20)
    private String phone;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false)
    private UserStatus status = UserStatus.ACTIVE;

    @CreationTimestamp
    @Column(updatable = false)
    private LocalDateTime createdAt;

    @CreationTimestamp
    private  LocalDateTime updatedAt;
}
