spring:
  application:
    name: event-manager
  config:
    import: configserver:http://localhost:6971
  profiles:
    active: local
  cloud:
    config:
      profile: default

server:
  port: 7070

eureka:
  client:
    service-url:
      defaultZone: http://localhost:6969/eureka