spring:
  application:
    name: event-manager
  profiles:
    active: local
  main:
    allow-bean-definition-overriding: true
  config:
    import: configserver:http://localhost:6971
  cloud:
    config:
      profile: default
      override-none: false
      fail-fast: false


  devtools:
    restart:
      enabled: true

server:
  port: 7070

eureka:
  client:
    service-url:
      defaultZone: http://localhost:6969/eureka/