spring:
  application:
    name: event-manager
  config:
    import: optional:configserver:http://localhost:6971
  profiles:
    active: local

server:
  port: 7070

eureka:
  client:
    service-url:
      defaultZone: http://localhost:6969/eureka