spring:
  application:
    name: log-manager
  config:
    import: configserver:http://localhost:6971
  profiles:
    active: local

server:
  port: 7074

eureka:
  client:
    service-url:
      defaultZone: http://localhost:6969/eureka