spring:
  application:
    name: api-gateway
  config:
    import: configserver:http://localhost:6971

server:
  port: 6970

eureka:
  client:
    service-url:
      defaultZone: http://localhost:6969/eureka

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true

springdoc:
  api-docs:
    path: /gateway/api-docs
  swagger-ui:
    enabled: false