spring:
  application:
    name: api-gateway
  config:
    import: configserver:http://localhost:6971
  cloud:
    gateway:
      mvc:
        http-client:
          connect-timeout: 3000
          read-timeout: 10000
    loadbalancer:
      eager-load:
        enabled: true
        clients:
          - AUTH-MANAGER
          - EVENT-MANAGER
          - LOG-MANAGER
          - ENGAGEMENT-MANAGER
          - EXPENSE-MANAGER
          - VENUE-MANAGER
          - VENDOR-MANAGER

      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins:
              - "http://localhost:5173"
            allowed-methods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - OPTIONS
            allowed-headers:
              - "*"
            allow-credentials: true
            max-age: 3600

server:
  port: 6970

eureka:
  client:
    service-url:
      defaultZone: http://localhost:6969/eureka
    registry-fetch-interval-seconds: 5
    initial-instance-info-replication-interval-seconds: 5

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
  health:
    circuitbreakers:
      enabled: true

springdoc:
  api-docs:
    path: /gateway/api-docs
  swagger-ui:
    enabled: false