spring:
  application:
    name: engagement-manager
  config:
    import: "configserver:http://localhost:6971"
  cloud:
    config:
      profile: default
  profiles:
    active: local

server:
  port: 7071

eureka:
  client:
    service-url:
      defaultZone: http://localhost:6969/eureka
  instance:
    prefer-ip-address: true

services:
  event:
    url: http://localhost:7070
  auth:
    url: http://localhost:7069

