spring:
  application:
    name: engagement-manager
  config:
    import: "optional:http://localhost:6971"
  profiles:
    active: local
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  devtools:
    restart:
      enabled: true

server:
  port: 7071

eureka:
  client:
    service-url:
      defaultZone: http://localhost:6969/eureka
  instance:
    prefer-ip-address: true

services:
  event:
    url: http://localhost:7070
  auth:
    url: http://localhost:7069

logging:
  level:
    org.springframework.web: DEBUG
