spring:
  application:
    name: venue-manager
  config:
    import: "configserver:http://localhost:6971"
  profiles:
    active: local

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    disable-swagger-default-url: true
    path: /api/v1/venue-manager
  packages-to-scan: com.cts.venue_manager.controller

logging:
  level:
    org.springdoc: DEBUG

eureka:
  client:
    service-url:
      defaultZone: http://localhost:6969/eureka

server:
  port: 7076